version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo Packaging Lambda function...
      - zip -r cleanup.zip .

artifacts:
  files:
    - cleanup.zip
